###############################################################################################################################################################################################################################################################
[package]
	authors      = ['OST-Gh']
	categories   = ['command-line-utilities']
	description  = ''
	edition      = '2021'
	keywords     = ['toml']
	license-file = 'LICENSE'
	name         = 'prata'
	readme       = 'README.md'
	version      = '0.0.0'
###############################################################################################################################################################################################################################################################
[[bin]]
	name = 'prata'
	path = 'src/main.rs'
###############################################################################################################################################################################################################################################################
[dependencies]
	thiserror = '1'
